version: '3.8'

services:
  # Jenkins Master
  jenkins:
    image: jenkins/jenkins:lts
    container_name: opticash-jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
      - JENKINS_OPTS=--httpPort=8080
    restart: unless-stopped
    networks:
      - jenkins-network
    labels:
      - "com.opticash.service=jenkins"

  # Jenkins Agent (opcional)
  jenkins-agent:
    image: jenkins/inbound-agent:latest
    container_name: opticash-jenkins-agent
    environment:
      - JENKINS_URL=http://jenkins:8080
      - JENKINS_SECRET=your-secret-here
      - JENKINS_AGENT_NAME=opticash-agent
    depends_on:
      - jenkins
    networks:
      - jenkins-network
    labels:
      - "com.opticash.service=jenkins-agent"

volumes:
  jenkins_home:
    driver: local

networks:
  jenkins-network:
    driver: bridge
    name: jenkins-network
